### ISSUE TITLE
Add button style

### ISSUE THREAD

**Issue by david-webber** [david-webber/Uncouth-css#10]
Add a button style, with hover and disabled states. This should apply to both the button element and input type=submit.

Please see the contributing guidelines in [readme.md](https://github.com/david-webber/Uncouth-css/blob/main/README.md)

**Comment by plushugh** [comment]
I'll do it, assign it to me so I can give it a go😀

**Comment by plushugh** [comment]
Should I add a sass file(button.scss in the components directory or do something else?(e.g. add it in the forms.scss file)

**Comment by david-webber** [comment]
@plushugh 

I'm happy for you to add the button style in either button.scss, other.scss or forms.scss. I'll leave it up to you.

Thanks.
