### ISSUE TITLE
Dark Mode doesn't apply to form inputs

### ISSUE THREAD

**Issue by plushugh** [david-webber/Uncouth-css#11]
Steps to reproduce:
- Turn on dark mode on the browser or system(In my case it's windows 10 settings)
- Visit [demo](https://david-webber.github.io/Uncouth-css/)
- The form demo doesn't have any dark-mode specific styles

**Comment by david-webber** [comment]
@plushugh - yeah I did notice this after I accepted the first form PR. If it is not dealt with in issue #9 I will sort it out after.

Thanks for highlighting it anyway. :)

**Comment by david-webber** [comment]
Fixed in #13
