### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by eydun** [david-webber/Uncouth-css#18]
Thank you for building this fine solution.

If I need to add a navigation-menu to the page, can you recommend any solution for this?

**Comment by david-webber** [comment]
Sorry for the delayed reply, didn't notice this issue and missed the notification! 

I'm sure you have resolved your issue now.

This library is supposed to be a simple unopinionated starter, so adding any specific navigation is out of scope.

I would recommend using this library as a starting point (if you wanted to) and coding your own, or adding another 3rd party navigation CSS on top.
