### ISSUE TITLE
Add a table

### ISSUE THREAD

**Issue by david-webber** [david-webber/Uncouth-css#2]
Add a table to the index.html page and styles to the tables.scss file.

The table should not have a border and make use of the 'background-mid' variable for alternating row background colours.

**Comment by mgilberties** [comment]
Can I have a go at this please? Is there any other style requirements apart from no border and alternate row colours?

**Comment by david-webber** [comment]
Hi @mgilberties , apologies for the delay I have just seen this. 

I have assigned this to you. No other style requirements I'm happy for you to tackle this however you feel is best. 

Thanks!
