### ISSUE TITLE
Add Form Elements

### ISSUE THREAD

**Issue by david-webber** [david-webber/Uncouth-css#9]
The last PR only added a couple of form elements, we need a full example of all form elements in the demo with associated style.

See: https://www.w3schools.com/html/html_form_elements.asp

Please see the contributing guidelines in [readme.md](https://github.com/david-webber/Uncouth-css/blob/main/README.md)

**Comment by anushri20** [comment]
Hi, Can I work on this?

**Comment by david-webber** [comment]
@anushri20 sure! I have just assigned you.

Thanks.

**Comment by anushri20** [comment]
@david-webber  Hi, I am getting this error while running npm run compile. Can you please help me out? 

![image](https://user-images.githubusercontent.com/49443274/95435601-69be5300-0970-11eb-86f1-bff9a97ced50.png)


Thank you!

**Comment by david-webber** [comment]
@anushri20 - Apologies for the delay, I'm just on my lunch break from work. I have just taken a look and it appears to be an issue on windows. I will update the package.json in a second so it will be fixed for you, I will look into the bigger issue further this evening when I finish work. Thanks for highlighting.

**Comment by david-webber** [comment]
@anushri20 I have just updated the scripts in the package.json file, and it appears to be working on my windows machine. Can you please pull the change and try again?

Thanks.

**Comment by anushri20** [comment]
Yeah, Thanks it's working now.

**Comment by sptutusukanta** [comment]
Hi there, is anyone still working on it? If no, then I may be of some help. @david-webber, please let me know.

**Comment by david-webber** [comment]
@sptutusukanta it doesn't look like this is being worked on anymore. I was going to finish this CSS library after hacktobefest but wanted to give people the chance to contribute first.

Feel free to work on it.

Thanks.

**Comment by anushri20** [comment]
@david-webber Apologies for delay, I was sick so couldn't  look to the changes. It seems like someone is working on this, if you still need any changes in the PR please let me know.

Thanks.

**Comment by sptutusukanta** [comment]
> @sptutusukanta it doesn't look like this is being worked on anymore. I was going to finish this CSS library after hacktobefest but wanted to give people the chance to contribute first.
> 
> Feel free to work on it.
> 
> Thanks.

Thanks for your quick response, can you lease assign for the task, as per your contributing info.

**Comment by sptutusukanta** [comment]
Hi @david-webber, did you get time to check the PR? Any thoughts?
